apiVersion: v1
kind: ConfigMap
metadata:
  name: prediction-service-config
  namespace: car-marketplace
  labels:
    app.kubernetes.io/name: prediction-service
    app.kubernetes.io/part-of: car-marketplace
data:
  MODEL_EXPORT_DIR: /app/export
  API_PORT: "8083"
