apiVersion: v1
kind: ConfigMap
metadata:
  name: prediction-service-config
  namespace: car-marketplace
  labels:
    app.kubernetes.io/name: prediction-service
    app.kubernetes.io/part-of: car-marketplace
data:
  MODEL_EXPORT_DIR: /app/export
  CACHE_HOST: cache-service.car-marketplace.svc.cluster.local
  CACHE_PORT: "6379"
  API_PORT: "8083"
