apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-example-com
  namespace: car-marketplace
spec:
  secretName: api-146-190-205-209-nip-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - api.146.190.205.209.nip.io
