apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-146-190-205-209-nip-io
  namespace: monitoring
spec:
  secretName: grafana-146-190-205-209-nip-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - grafana.146.190.205.209.nip.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-146-190-205-209-nip-io
  namespace: monitoring
spec:
  secretName: prometheus-146-190-205-209-nip-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prometheus.146.190.205.209.nip.io
