apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: car-marketplace
  labels:
    app.kubernetes.io/name: cache-service
    app.kubernetes.io/part-of: car-marketplace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cache-service
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
