#cloud-config
package_update: true
packages:
  - curl
  - ca-certificates

users:
  - name: ubuntu
    gecos: Ubuntu
    groups:
      - adm
      - sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_public_key}

write_files:
  - path: /usr/local/bin/install-k3s-worker.sh
    owner: root:root
    permissions: "0755"
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      PRIVATE_IP="$(curl -fsSL http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)"

      until timeout 2 bash -c "</dev/tcp/${master_private_ip}/6443" >/dev/null 2>&1; do
        sleep 5
      done

      if [ -n "${k3s_version}" ]; then
        export INSTALL_K3S_VERSION="${k3s_version}"
      fi

      curl -sfL https://get.k3s.io | \
        K3S_URL="https://${master_private_ip}:6443" \
        K3S_TOKEN="${k3s_token}" \
        INSTALL_K3S_EXEC="agent --node-ip $PRIVATE_IP" \
        sh -

runcmd:
  - [bash, -lc, /usr/local/bin/install-k3s-worker.sh]
