apiVersion: v1
kind: Namespace
metadata:
  name: car-marketplace
  labels:
    app.kubernetes.io/part-of: car-marketplace
    environment: production
apiVersion: v1
kind: Namespace
metadata:
  name: car-marketplace
  labels:
    app.kubernetes.io/part-of: car-marketplace
    environment: production
