apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-service
  template:
    metadata:
      labels:
        app: prediction-service
    spec:
      containers:
        - name: prediction-service
          image: ghcr.io/henrik-13/car-marketplace-prediction-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: prediction-service-config
            - secretRef:
                name: prediction-service-secret
