apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: car-marketplace
  labels:
    app.kubernetes.io/name: prediction-service
    app.kubernetes.io/part-of: car-marketplace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prediction-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
